import Head from 'next/head';
import Sidebar from '../components/Sidebar';
import styled from 'styled-components';
import Image from 'next/image';

export default function Home() {
  const rotateCardBack = () => {
    const back = document.getElementById('back');
    const front = document.getElementById('front');

    front.style.transform = `rotateY(-180deg)`;
    back.style.transform = 'rotateY(0)';
  };

  const rotateCardFront = () => {
    const back = document.getElementById('back');
    const front = document.getElementById('front');

    front.style.transform = `rotateY(0)`;
    back.style.transform = 'rotateY(-180deg)';
  };

  return (
    <div>
      <Head>
        <title>Home | Vipi</title>
        <meta name="description" content="Generated by AK The Dev" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <DefaultContainer>
        <Sidebar />
        <DefaultHome>
          <div className="card">
            <div className="card__side  card__side--back" id="back">
              <div className="backtofront" onClick={rotateCardFront}>
                &larr;
              </div>
              <h4
                style={{
                  margin: '8rem 3rem 0 3rem',
                  fontSize: '2rem',
                  borderBottom: '1px solid gray',
                  paddingBottom: '.7rem',
                  letterSpacing: '.6px',
                }}
              >
                Current Features :
              </h4>
              <ul
                style={{
                  fontSize: 15.5,
                  color: '#343A40',
                  margin: '1.5rem 0 0 5.5rem',
                  lineHeight: 1.6,
                }}
              >
                <li>Login & Logout</li>
                <li>Add Chat</li>
                <li>Search Chat</li>
                <li>Delete Chat</li>
                <li>Chat with individual user</li>
                <li>Send Emoji&apos;s</li>
                <li>Auto scroll to last message</li>
                <li>
                  <a
                    href="https://github.com/Ajay-056/Whatsapp-Clone-NextJS/tags"
                    target="_blank"
                    rel="noreferrer"
                  >
                    Click here to see the release change log...
                  </a>
                </li>
              </ul>
             
            </div>
            <div className="card__side card__side--front" id="front">
         

              <p
                style={{
                  margin: '5rem 3rem 0.5rem 3rem',
                  letterSpacing: '0px',
                  fontSize: '1.6rem',
                  lineHeight: 1.5,
                  color: '#212529',
                  textAlign: 'left',
                }}
              >
                Welcome to the Whatsapp clone made from Next JS, React JS and
                Firebase.
              </p>
              <h4
                style={{
                  margin: '4rem 3rem 0 3rem',
                  fontSize: '2rem',
                  borderBottom: '1px solid gray',
                  paddingBottom: '.7rem',
                  letterSpacing: '.6px',
                }}
              >
                Get started :
              </h4>
              <ul
                style={{
                  fontSize: 15.5,
                  color: '#343A40',
                  margin: '1.5rem 0 0 5.5rem',
                  lineHeight: 1.6,
                }}
              >
                <li> To start chatting click the add button below</li>
                <li>Enter the Google email account of the user to chat with</li>
                <li>The user account should be saved on your chat list</li>
                <li> Click on the account to start chatting</li>
              </ul>
              <div
                style={{
                  display: 'flex',
                  alignItems: 'center',
                  justifyContent: 'center',
                  marginTop: '5rem',
                }}
              >
                <button
                  type="button"
                  className="btn"
                  onClick={rotateCardBack}
                  style={{
                    padding: '1.2rem 2rem',
                    backgroundColor: 'rebeccapurple',
                    border: '0px',
                    outline: 0,
                    color: '#fff',
                    borderRadius: '5px',
                    fontSize: '1.7rem',
                    cursor: 'pointer',
                  }}
                >
                  Know More &rarr;
                </button>
              </div>
            </div>
          </div>
        </DefaultHome>
      </DefaultContainer>
    </div>
  );
}

const DefaultContainer = styled.div`
  display: flex;
`;

const DefaultHome = styled.div`
  display: flex;
  flex: 1;
  height: 100vh;
  justify-content: center;
  align-items: center;
`;

// const InfoBox = styled.div`
//   height: 60rem;
//   width: 56rem;
//   background-color: #99d98c;
//   font-weight: 500;
//   font-size: 1.4rem;
//   border-radius: 1rem;
//   box-shadow: 0 20px 30px 0 rgba(0, 0, 0, 0.19);
// `;
